VAGRANTFILE_API_VERSION = "2";

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "confluent-dev"

  config.vm.provider "virtualbox" do |vb|
    # If the VM's RAM is less than 2GB, change the JVM heap sizes (check provision.sh)
    vb.memory = 2048

  end

  config.vm.provision "shell", path: "provision.sh"
  config.vm.network "forwarded_port", guest: 8082, host: 8082, id: "confluent-api"

end
